THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_A.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_B.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_C.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_D.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_E.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_F.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_G.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_H.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_I.yaml
THEANO_FLAGS="device=gpu0" python extract_features.py config/6x6/extract/H_interm_exp_h_3_train_J.yaml
