git add *.py
git add */*.py
git add */*/*.py
git add */*/*/*.py
git add */*/*/*/*.py
git add */*/*/*/*/*.py
git add */*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*/*.py
git add *.m
git add */*.m
git add */*/*.m
git add */*/*/*.m
git add */*/*/*/*.m
git add */*/*/*/*/*.m
git add */*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*/*/*.m
git add */*.yaml
git add */*/*.yaml
git add */*/*/*.yaml
git add */*/*/*/*.yaml
git add */*/*/*/*/*.yaml
git add */*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*/*/*.yaml
git add */*.sh
git add */*/*.sh
git add */*/*/*.sh
git add */*/*/*/*.sh
git add */*/*/*/*/*.sh
git add */*/*/*/*/*/*.sh
git add */*/*/*/*/*/*/*.sh
git add */*/*/*/*/*/*/*/*.sh
git add */*/*/*/*/*/*/*/*/*.sh
git add */Makefile
git add */*/Makefile
git add */*/*/Makefile
git add */*/*/*/Makefile
git add */*/*/*/*/Makefile
git add */*/*/*/*/*/Makefile
git add */*/*/*/*/*/*/Makefile
git add */*/*/*/*/*/*/*/Makefile
git add */*/*/*/*/*/*/*/*/Makefile
git add */*.c
git add */*/*.c
git add */*/*/*.c
git add */*/*/*/*.c
git add */*/*/*/*/*.c
git add */*/*/*/*/*/*.c
git add */*/*/*/*/*/*/*.c
git add */*/*/*/*/*/*/*/*.c
git add */*/*/*/*/*/*/*/*/*.c
git add */*.cpp
git add */*/*.cpp
git add */*/*/*.cpp
git add */*/*/*/*.cpp
git add */*/*/*/*/*.cpp
git add */*/*/*/*/*/*.cpp
git add */*/*/*/*/*/*/*.cpp
git add */*/*/*/*/*/*/*/*.cpp
git add */*/*/*/*/*/*/*/*/*.cpp
git add */*.pdf
git add */*/*.pdf
git add */*/*/*.pdf
git add */*/*/*/*.pdf
git add */*/*/*/*/*.pdf
git add */*/*/*/*/*/*.pdf
git add */*/*/*/*/*/*/*.pdf
git add */*/*/*/*/*/*/*/*.pdf
git add */*/*/*/*/*/*/*/*/*.pdf
git add */*.lyx
git add */*/*.lyx
git add */*/*/*.lyx
git add */*/*/*/*.lyx
git add */*/*/*/*/*.lyx
git add */*/*/*/*/*/*.lyx
git add */*/*/*/*/*/*/*.lyx
git add */*/*/*/*/*/*/*/*.lyx
git add */*/*/*/*/*/*/*/*/*.lyx
