git add *.py
git add */*.py
git add */*/*.py
git add */*/*/*.py
git add */*/*/*/*.py
git add */*/*/*/*/*.py
git add */*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*/*.py
