git add *.py
git add */*.py
git add */*/*.py
git add */*/*/*.py
git add */*/*/*/*.py
git add */*/*/*/*/*.py
git add */*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*.py
git add */*/*/*/*/*/*/*/*/*.py
git add *.m
git add */*.m
git add */*/*.m
git add */*/*/*.m
git add */*/*/*/*.m
git add */*/*/*/*/*.m
git add */*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*/*.m
git add */*/*/*/*/*/*/*/*/*.m
git add */*.yaml
git add */*/*.yaml
git add */*/*/*.yaml
git add */*/*/*/*.yaml
git add */*/*/*/*/*.yaml
git add */*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*/*.yaml
git add */*/*/*/*/*/*/*/*/*.yaml
