makebatches
load stitched
data = batchdata(:,:,1);
targets = batchtargets(:,:,1);


% Before running this script, I edited mf to  *always* run for 10 iterations
% In Russ's PCD training code, it runs for *up to* 10 iterations.
[poshidprobs, pospenprobs] = ...
         mf(data,targets,vishid,hidbiases,visbiases,hidpen,penbiases,labpen,0.);

numcases = size(data,1);
bias_lab = repmat(labbiases,numcases,1);
totin =  bias_lab + pospenprobs*labpen';
poslabprobs1 = exp(totin);
numlab = size(targets,2);
targetout = poslabprobs1./(sum(poslabprobs1,2)*ones(1,numlab));
[I J]=max(targetout,[],2);
[I1 J1]=max(targets,[],2);
correct=length(find(J==J1))
save('pylearn2_test_data.mat', ...
      'data', ...
      'targets', ...
      'vishid', ...
      'hidbiases', ...
      'visbiases', ...
      'hidpen', ...
      'penbiases', ...
      'labpen', ...
      'poshidprobs', ...
      'pospenprobs', ...
      'targetout', ...
      'labbiases', ...
      'correct')

